<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Rocket League 2v2 Turnier — MilanHD</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&display=swap');
    body{margin:0;font-family:'Orbitron',sans-serif;background:radial-gradient(circle at top,#0a0f1f,#000);color:#fff;overflow-x:hidden}
    header{padding:30px;text-align:center;position:relative;z-index:10}
    header h1{font-size:3rem;margin:0;color:#ff6600;text-shadow:0 0 15px #ff6600}
    header p{color:#aaa;margin-top:10px;font-size:1.2rem}
    .hero{height:90vh;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:30px;text-align:center;position:relative;z-index:5}
    .hero h2{font-size:2.5rem;margin:0;text-shadow:0 0 20px #00f6ff}
    .cta-btn{padding:18px 36px;background:#ff6600;color:#000;font-weight:700;border-radius:50px;font-size:1.3rem;text-decoration:none;transition:transform .2s, box-shadow .2s}
    .cta-btn:hover{transform:scale(1.1);box-shadow:0 0 25px #ff6600}
    .links{display:flex;gap:20px;flex-wrap:wrap;justify-content:center;margin-top:20px}
    .links a{padding:12px 20px;border-radius:30px;text-decoration:none;color:#fff;background:#111;border:1px solid #333;transition:all .2s}
    .links a:hover{background:#ff6600;color:#000;box-shadow:0 0 15px #ff6600}
    .section{padding:60px 20px;text-align:center;position:relative;z-index:5}
    .section h2{font-size:2rem;color:#00f6ff;text-shadow:0 0 15px #00f6ff;margin-bottom:20px}
    .neon{color:#ff6600;text-shadow:0 0 20px #ff6600,0 0 40px #ff6600}
    footer{padding:30px;text-align:center;color:#aaa;font-size:.9rem;background:#05050a}
    /* background orbs */
    .orb{position:absolute;border-radius:50%;filter:blur(100px);opacity:.4;animation:float 12s ease-in-out infinite}
    .orb1{width:400px;height:400px;background:#ff6600;top:-100px;left:-100px}
    .orb2{width:300px;height:300px;background:#00f6ff;bottom:-100px;right:-100px;animation-delay:6s}
    @keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-60px)}}
  </style>
</head>
<body>
  <div class="orb orb1"></div>
  <div class="orb orb2"></div>
  
  <header>
    <h1>Rocket League 2v2 Turnier</h1>
    <p>Organisiert von <span class="neon">MilanHD</span></p>
  </header>

  <section class="hero">
    <h2>Bist du bereit für das krasseste 2v2 Turnier?</h2>
    <a class="cta-btn" href="#anmeldung">Jetzt anmelden</a>
    <div class="links">
      <a href="https://www.youtube.com/@hundel1.012/videos" target="_blank">YouTube</a>
      <a href="https://discord.gg/4rHS8zhSMa" target="_blank">Discord</a>
    </div>
  </section>

  <section class="section" id="info">
    <h2>Turnier-Info</h2>
    <p>8 Teams, 2v2, Gruppenphase & Playoffs. Action, Spannung und Neon-Vibes. Sei dabei und kämpfe um Ruhm und Ehre!</p>
  </section>

  
<section class="section" id="anmeldung">
  <h2>Anmeldung</h2>
  <p>Klick auf den Button und du wirst direkt zum Anmeldeformular weitergeleitet!</p>
  <a class="cta-btn" href="https://docs.google.com/forms/d/1I9moj8QmouBbIcPdpJxwio7UWd4CTSmeTh8y0KQcoAw/viewform" target="_blank">
    Zum Anmeldeformular
  </a>
  <p style="margin-top:20px;color:#aaa">
    (Wenn du dich anmelden willst, öffne bitte das Formular und trage Teamname, Spieler und Kontakt ein)
  </p>
</section>

  <footer>
    <p>© 2025 Rocket League 2v2 Turnier von MilanHD | Nicht offiziell mit Psyonix verbunden</p>
  </footer>
</body>
</html>
